### ISSUE TITLE
找不到路径或文件

### ISSUE THREAD

**Issue by doudoubinga** [shibing624/textgen#2]
完整错误信息
2022-07-11 11:25:44.675 | INFO     | textgen.unsup_generation.tgls_model:__init__:36 - docs_text len: 3
Traceback (most recent call last):
  File "C:\Downloads\Compressed\textgen-main\examples\unsup_generation_demo.py", line 31, in <module>
    m = TglsModel(docs_text)
  File "C:\AppData\Roaming\Python\Python310\site-packages\textgen\unsup_generation\tgls_model.py", line 38, in __init__
    self.stopwords = set(load_list(default_stopwords_path))
  File "C:\AppData\Roaming\Python\Python310\site-packages\textgen\unsup_generation\phrase.py", line 131, in load_list
    return [l for l in open(path, 'r', encoding='utf-8').read().split()]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AppData\\Roaming\\Python\\Python310\\site-packages\\textgen\\unsup_generation\\../data/stopwords.txt'

这个错误是在运行例子的时候出现的，操作系统win10，python版本3.10.5
[unsup_generation_demo.py](https://github.com/shibing624/textgen/blob/main/examples/unsup_generation_demo.py)

请问要怎么解决，谢谢

**Comment by shibing624** [comment]
更新代码到v0.1.2，fixed。

**Comment by bingxin3chen** [comment]
徐老师您好，我的版本已更新到 v0.1.2，但依旧存在图片中的问题。
版本：
![image](https://user-images.githubusercontent.com/89672905/182794846-71a21318-e03d-45e8-a6be-74cfd316edc8.png)
报错信息：
![image](https://user-images.githubusercontent.com/89672905/182795463-4af76904-53d4-4021-a447-9ae46579c91f.png)

**Comment by shibing624** [comment]
fixed. https://github.com/shibing624/textgen/commit/40d5544fead05a400e351f11bbebaa2c7b3189fa
