### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by yeyuan0620** [shibing624/textgen#59]
### Describe the Question
Please provide a clear and concise description of what the question is.

**Comment by yeyuan0620** [comment]
root@autodl-container-176e4f97d8-1a1babc9:~/autodl-tmp/textgens# python examples/T5/gradio_demo.py
Traceback (most recent call last):
  File "examples/T5/gradio_demo.py", line 10, in <module>
    from textgen import T5Model
  File "/root/miniconda3/lib/python3.8/site-packages/textgen-1.1.1-py3.8.egg/textgen/__init__.py", line 15, in <module>
    from textgen.language_modeling.language_modeling_model import LanguageModelingModel
  File "/root/miniconda3/lib/python3.8/site-packages/textgen-1.1.1-py3.8.egg/textgen/language_modeling/__init__.py", line 8, in <module>
    from textgen.language_modeling.language_modeling_model import LanguageModelingModel
  File "/root/miniconda3/lib/python3.8/site-packages/textgen-1.1.1-py3.8.egg/textgen/language_modeling/language_modeling_model.py", line 62, in <module>
    from textgen.custom_models.models import ElectraForLanguageModelingModel
  File "/root/miniconda3/lib/python3.8/site-packages/textgen-1.1.1-py3.8.egg/textgen/custom_models/models.py", line 30, in <module>
    from transformers.models.distilbert.modeling_distilbert import DISTILBERT_PRETRAINED_MODEL_ARCHIVE_LIST
ImportError: cannot import name 'DISTILBERT_PRETRAINED_MODEL_ARCHIVE_LIST' from 'transformers.models.distilbert.modeling_distilbert' (/root/miniconda3/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py)

**Comment by yeyuan0620** [comment]
我在部署时出现这个问题，请问怎么解决

**Comment by shibing624** [comment]
transformers 版本问题，你用的哪个版本的transformers，我兼容下

**Comment by yeyuan0620** [comment]
解决了，tansformer4.30.2就可以，谢谢

**Comment by yulinfeng16** [comment]
同问

而且transformers4.30.2引用的tokenizers0.13.3 Rust编译会有问题……
