### ISSUE TITLE
training_copyt5_model_demo.py

### ISSUE THREAD

**Issue by ytWu1314** [shibing624/textgen#60]
```
2024-09-10 12:51:51.461 | INFO     | textgen.t5.copyt5_utils:__init__:202 -  Saving features into cached file cache_dir/imxly_t5-copy_cached_320699
Generating outputs:   0%|                                | 0/88 [00:00<?, ?it/s]
Epoch 1 of 10:   0%|                                     | 0/10 [04:51<?, ?it/s]
Traceback (most recent call last):
  File "training_copyt5_model_demo.py", line 154, in <module>
    main()
  File "training_copyt5_model_demo.py", line 131, in main
    model.train_model(train_df, eval_data=eval_df, matches=count_matches)
  File "/root/autodl-tmp/textgen-main/examples/T5/../../textgen/t5/copyt5_model.py", line 204, in train_model
    global_step, training_details = self.train(
  File "/root/autodl-tmp/textgen-main/examples/T5/../../textgen/t5/copyt5_model.py", line 726, in train
    results = self.eval_model(
  File "/root/autodl-tmp/textgen-main/examples/T5/../../textgen/t5/copyt5_model.py", line 907, in eval_model
    preds = self.predict(to_predict)
  File "/root/autodl-tmp/textgen-main/examples/T5/../../textgen/t5/copyt5_model.py", line 1006, in predict
    outputs = self.model.generate(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1322, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/root/autodl-tmp/textgen-main/examples/T5/../../textgen/custom_models/models.py", line 780, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"] = encoder(input_ids, return_dict=True, **new_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 993, in forward
    assert self.is_decoder, f"`use_cache` can only be set to `True` if {self} is used as a decoder"
AssertionError: `use_cache` can only be set to `True` if T5Stack(
```
Copyt5这部分的代码有问题，没办法复现。请问作者复现过吗？

**Comment by shibing624** [comment]
复现过

**Comment by ytWu1314** [comment]
> 复现过

请问作者能不能提供一下复现的环境？主要是transformers的版本和torch的版本，这个代码在现在的transformers t5里面会报错。

**Comment by shibing624** [comment]
fixed
